export default {
    login: "chasegarsee",
    id: 47544678,
    node_id: "MDQ6VXNlcjQ3NTQ0Njc4",
    avatar_url: "https://avatars.githubusercontent.com/u/47544678?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/chasegarsee",
    html_url: "https://github.com/chasegarsee",
    followers_url: "https://api.github.com/users/chasegarsee/followers",
    following_url: "https://api.github.com/users/chasegarsee/following{/other_user}",
    gists_url: "https://api.github.com/users/chasegarsee/gists{/gist_id}",
    starred_url: "https://api.github.com/users/chasegarsee/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/chasegarsee/subscriptions",
    organizations_url: "https://api.github.com/users/chasegarsee/orgs",
    repos_url: "https://api.github.com/users/chasegarsee/repos",
    events_url: "https://api.github.com/users/chasegarsee/events{/privacy}",
    received_events_url: "https://api.github.com/users/chasegarsee/received_events",
    type: "User",
    site_admin: false,
    name: "Chase Garsee",
    company: "Preemptive Love Coalition",
    blog: "https://chasegarsee.com",
    location: "Nashville, TN.",
    email: null,
    hireable: true,
    bio: null,
    twitter_username: "chasegarsee",
    public_repos: 105,
    public_gists: 3,
    followers: 4,
    following: 0,
    created_at: "2019-02-11T23:57:40Z",
    updated_at: "2021-01-24T15:13:45Z",
  }